import {bindEditorControls} from './editor-controls.mjs';
import {encodeQuote,decodeQuote} from './share.mjs';
import {shouldOfferDraftRestore,freshQuote,defaultQuote,sanitizeQuote,validateQuote,calculateTotalCost,calculateInstallment,calculateMvno,NUMERIC} from './calculate.mjs';
import {editorView,addonView,resultView,field,money,esc} from './views.mjs';
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
const base=document.body.dataset.base||'',route=p=>base+p+'/';
const cfg=await fetch(base+'/assets/site.json').then(r=>{if(!r.ok)throw new Error('설정 정보를 불러오지 못했습니다. 새로고침해주세요.');return r.json();});
const KEYS={saved:'phone-cost.v1.saved',compare:'phone-cost.v1.compare',draft:'phone-cost.v1.draft',check:'phone-cost.v1.check',editing:'phone-cost.v2.editing',comparePeriod:'phone-cost.v1.comparePeriod'};
let notificationTimer;
function toast(msg){$('#toast').textContent=msg;clearTimeout(notificationTimer);notificationTimer=setTimeout(()=>$('#toast').textContent='',5000);}
function read(key,fallback){try{const raw=localStorage.getItem(KEYS[key]);return raw?JSON.parse(raw):fallback;}catch{toast('저장 데이터를 읽지 못했습니다. 브라우저 저장 설정을 확인하세요.');return fallback;}}
function write(key,value){try{localStorage.setItem(KEYS[key],JSON.stringify(value));return true;}catch{toast('저장 공간이 부족하거나 브라우저 저장이 차단되었습니다. 링크나 이미지로 보관하세요.');return false;}}
function entries(key){const rows=read(key,[]);if(!Array.isArray(rows))return [];return rows.slice(0,100).flatMap(x=>{try{return [{id:String(x.id),q:sanitizeQuote(x.q),updated:String(x.updated||''),period:[24,36].includes(x.period)?x.period:24}];}catch{return [];}});}
function actionDialog(message,fn,initial=null){
 const d=document.createElement('dialog');d.setAttribute('aria-labelledby','action-title');
 d.innerHTML=`<h2 id="action-title">${esc(message)}</h2>${initial!==null?`<label class="field"><span>새 견적 이름</span><input type="text" name="newName" maxlength="80" value="${esc(initial)}" required></label>`:''}<p class="error-box" role="alert"></p><div class="actions" style="margin-top:20px"><button type="button" data-cancel>취소</button><button type="button" class="primary" data-confirm>확인</button></div>`;
 document.body.append(d);const close=()=>{d.close();d.remove();};d.querySelector('[data-cancel]').onclick=close;d.addEventListener('cancel',()=>d.remove());d.querySelector('[data-confirm]').onclick=()=>{const value=initial!==null?d.querySelector('input').value.trim():null;if(initial!==null&&(!value||value.length>80)){d.querySelector('[role=alert]').textContent='이름을 1~80자로 입력하세요.';return;}close();fn(value);};d.showModal();if(initial!==null)d.querySelector('input').select();else d.querySelector('[data-cancel]').focus();
}
function confirmAction(message,fn){actionDialog(message,fn);}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
async function copy(text){try{await navigator.clipboard.writeText(text);toast('복사했습니다.');}catch{const d=$('#copy-dialog');d.querySelector('textarea').value=text;d.showModal();d.querySelector('textarea').select();}}
$('#close-dialog').onclick=()=>$('#copy-dialog').close();
$('#menu-toggle').onclick=()=>{const open=$('#main-nav').classList.toggle('open');$('#menu-toggle').setAttribute('aria-expanded',String(open));$('#menu-toggle').setAttribute('aria-label',open?'메뉴 닫기':'메뉴 열기');};
document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('#main-nav').classList.remove('open');$('#menu-toggle').setAttribute('aria-expanded','false');}});
function numericValue(input){const raw=input.value.replace(/,/g,'');if(!raw.trim())return NaN;if(!/^\d+(\.\d{1,2})?$/.test(raw))return NaN;const n=Number(raw);return Number.isFinite(n)?n:NaN;}
document.addEventListener('input',e=>{const x=e.target;if(x.matches('[data-number]')){const raw=x.value.replace(/,/g,'');if(raw===''||!/^\d*(\.\d{0,2})?$/.test(raw))return;const cursor=x.selectionStart,digits=x.value.slice(0,cursor).replace(/,/g,'').length;const [whole,fraction]=raw.split('.');x.value=(whole?Number(whole).toLocaleString('en-US'):'')+(fraction!==undefined?'.'+fraction:'');let count=0,pos=0;while(pos<x.value.length&&count<digits){if(x.value[pos]!==',')count++;pos++;}x.setSelectionRange(pos,pos);}});
function numericErrors(form){const errors=[];for(const input of form.querySelectorAll('[data-number]')){if(input.disabled)continue;const v=numericValue(input);const valid=Number.isFinite(v)&&v>=0&&v<=Number(input.dataset.max)&&(input.dataset.number==='decimal'||Number.isInteger(v));input.setAttribute('aria-invalid',String(!valid));if(!valid){const label=input.closest('label').querySelector('span').firstChild.textContent.trim();errors.push(`${label}: 0~${Number(input.dataset.max).toLocaleString('ko-KR')} 범위의 ${input.dataset.number==='decimal'?'숫자':'정수'}를 입력하세요.`);}}return errors;}
function showErrors(id,errors){const el=$(id);el.innerHTML=errors.length?`<strong>입력값을 확인해주세요.</strong><ul>${errors.map(e=>`<li>${esc(e)}</li>`).join('')}</ul>`:'';if(errors.length){document.querySelectorAll('[aria-invalid="true"]').forEach(x=>{let p=x.parentElement;while(p){if(p.tagName==='DETAILS')p.open=true;p=p.parentElement;}});el.focus();}}
function resultText(q,period){const r=calculateTotalCost(q,period);return `${cfg.brand}\n${period}개월 실제 총비용: ${money(r.total)}\n월평균: ${money(r.average)}\n기기 원금: ${money(r.device)}\n통신요금: ${money(r.plan)}\n부가서비스: ${money(r.addons)}\n보험: ${money(r.insurance)}\n기간 내 할부 비용: ${money(r.interest)}\n카드 연회비: ${money(r.cardFee)}\n카드 혜택: −${money(r.card)}\n기간 내 지출: ${money(r.cash)}\n남은 할부원금: ${money(r.remaining)}\n이후 할부 이자(총비용 제외): ${money(r.futureFee)}\n${q.cashOnly?'조건부 혜택 · 일시불 예상 비용. 카드·색상·결제 조건 확인 필요.':''}${q.priceNote?'\n'+q.priceNote:''}\n입력 조건에 따른 참고 계산입니다. 실제 계약 조건을 확인하세요.`;}
async function saveImage(q,period){const r=calculateTotalCost(q,period),canvas=document.createElement('canvas');canvas.width=1080;canvas.height=1260;const c=canvas.getContext('2d');c.fillStyle='#f5f7f8';c.fillRect(0,0,1080,1260);c.fillStyle='#172d3c';c.fillRect(48,48,984,350);c.font='bold 34px sans-serif';c.fillStyle='#b5e6d9';c.fillText(cfg.brand,90,120);c.fillStyle='#fff';c.font='30px sans-serif';c.fillText(`${period}개월 실제 총비용`,90,193);c.font='bold 70px sans-serif';c.fillText(money(r.total),90,285);c.font='28px sans-serif';c.fillText(`월평균 ${money(r.average)}`,90,350);const data=[['기기 원금',r.device],['통신요금',r.plan],['부가서비스',r.addons],['보험',r.insurance],['기간 내 할부 비용',r.interest],['카드 연회비 / 혜택',r.cardFee-r.card],['기간 내 실제 지출',r.cash],['남은 할부원금 (합계에 포함)',r.remaining]];c.fillStyle='#172d3c';data.forEach(([label,n],i)=>{const y=470+i*67;c.font='27px sans-serif';c.textAlign='left';c.fillText(label,90,y);c.textAlign='right';c.font='bold 29px sans-serif';c.fillText(money(n),984,y);});c.textAlign='left';c.font='23px sans-serif';c.fillStyle='#61717b';c.fillText(`기간 이후 할부 이자 ${money(r.futureFee)}는 합계에서 제외합니다.`,90,1060);c.fillText(q.cashOnly?'조건부 혜택 · 일시불 비교용. 카드·색상·결제 조건 확인 필수.':'입력 조건에 따른 참고 결과입니다. 실제 계약 조건을 확인하세요.',90,1110);c.fillText(q.cashOnly?'상세 구매 조건은 원본 견적에서 확인하세요.':`${new Date().toLocaleDateString('ko-KR')} · 개인 식별 정보 제외`,90,1160);canvas.toBlob(blob=>{if(blob){download(blob,'휴대폰-견적-요약.png');toast('요약 이미지를 저장했습니다.');}else toast('이미지 저장에 실패했습니다. 텍스트 복사를 이용하세요.');},'image/png');}
let current=freshQuote(cfg.policy.discountRate),analyzed=null,period=24,saveId=null,comparePeriod=[24,36].includes(read('comparePeriod',24))?read('comparePeriod',24):24;
let draftTimer=null,draftTouched=false;
function saveEditing(){
 if(!draftTouched||!$('#quote-form'))return;
 const form=$('#quote-form'),values={};
 for(const input of form.elements)if(input.name)values[input.name]=input.type==='checkbox'?input.checked:input.value;
 const snapshot={version:2,values,base:current,addonCount:form.querySelectorAll('[data-addon]').length,period,saveId,updated:new Date().toISOString()};
 if(write('editing',snapshot)&&$('#draft-status'))$('#draft-status').textContent='작성 중 내용 임시저장됨 · 이 기기에만 보관';
}
function queueDraft(){draftTouched=true;clearTimeout(draftTimer);draftTimer=setTimeout(saveEditing,300);}
function clearEditing(){clearTimeout(draftTimer);draftTouched=false;try{localStorage.removeItem(KEYS.editing);}catch{}$('#draft-restore')?.remove();}
window.addEventListener('pagehide',saveEditing);
function offerDraftRestore(){
 const draft=read('editing',null);if(!draft||draft.version!==2||!draft.values||typeof draft.values!=='object')return;
 const banner=document.createElement('section');banner.className='panel draft-banner';banner.id='draft-restore';
 banner.innerHTML='<strong>작성 중인 견적이 있습니다</strong><div class="actions"><button type="button" data-restore class="primary">이전 입력 복구</button><button type="button" data-discard>임시 입력 지우기</button></div>';
 $('#editor').prepend(banner);banner.querySelector('[data-discard]').onclick=()=>clearEditing();
 banner.querySelector('[data-restore]').onclick=()=>{
  try{
   const base={...freshQuote(cfg.policy.discountRate),...draft.base};
   for(const [k,max] of Object.entries(NUMERIC))if(!Number.isFinite(base[k])||base[k]<0||base[k]>max)base[k]=0;
   base.name='복구 중';base.model='복구 중';base.cashOnly=false;
   base.addons=Array.from({length:Math.min(30,Math.max(0,Number(draft.addonCount)||0))},()=>({name:'',cost:0,months:0}));
   const q=sanitizeQuote(base);q.cashOnly=draft.base?.cashOnly===true;
   period=[24,36].includes(draft.period)?draft.period:24;
   saveId=[...entries('saved'),...entries('compare')].some(x=>x.id===draft.saveId)?draft.saveId:null;analyzed=null;
   const controls=bindEditor(q),form=$('#quote-form');
   // Restore dependent model options before assigning their saved selections.
   if(typeof draft.values.catalogModel==='string')form.elements.catalogModel.value=draft.values.catalogModel;
   controls.renderCatalog(true);
   if(typeof draft.values.catalogStorage==='string')form.elements.catalogStorage.value=draft.values.catalogStorage;
   controls.refreshOffers();
   // Only existing form fields are restored. Unknown names cannot create DOM or code.
   for(const input of form.elements)if(input.name&&Object.hasOwn(draft.values,input.name)){
    const value=draft.values[input.name];if(input.type==='checkbox')input.checked=value===true;
    else if(typeof value==='string'&&value.length<=500)input.value=value;
   }
   controls.sync();controls.renderCatalog();banner.remove();queueDraft();
   $('#results').innerHTML='<section class="panel"><h2>입력을 복구했습니다.</h2><p>조건을 확인하고 다시 분석해주세요.</p></section>';
  }catch{toast('임시 입력을 복구할 수 없습니다. 새 견적을 입력해주세요.');}
 };
}
function fromForm(){const f=$('#quote-form'),q={...current};for(const k of Object.keys(NUMERIC)){const input=f.elements.namedItem(k);q[k]=input.disabled&&!Number.isFinite(numericValue(input))?(Number.isFinite(current[k])?current[k]:0):numericValue(input)};for(const k of ['name','model','priceMode','method','feeMode','planMode'])q[k]=f.elements.namedItem(k).value.trim();q.discount=f.elements.discount.value==='true';q.addons=Array.from(f.querySelectorAll('[data-addon]')).map(el=>{const i=el.dataset.addon;return{name:f.elements.namedItem('addonName'+i).value.trim(),cost:numericValue(f.elements.namedItem('addonCost'+i)),months:numericValue(f.elements.namedItem('addonMonths'+i))};});return q;}
function markDirty(){if(analyzed){$('#dirty').innerHTML='<p class="dirty-note">입력이 변경되었습니다. 아래 결과는 이전 분석입니다. 다시 분석하면 새 조건이 반영됩니다.</p>';$('#results').querySelectorAll('[data-action]').forEach(b=>b.disabled=true);}}
function bindEditor(q){current=q;$('#editor').innerHTML=editorView(q,cfg);const f=$('#quote-form');f.addEventListener('input',()=>{markDirty();queueDraft();});f.addEventListener('change',()=>{markDirty();queueDraft();});f.onsubmit=e=>{e.preventDefault();const inputErrors=numericErrors(f);const draft=fromForm();const errors=[...controls.validationErrors(),...inputErrors,...validateQuote(draft).filter(x=>!x.includes(': 0~'))];if(draft.planMode==='staged'&&draft.hold===0&&draft.plan>0&&draft.laterPlan===0)errors.push('초기 요금 유지가 0개월이고 이후 요금이 0원입니다. 같은 요금제 계속 사용 또는 변경 조건을 확인하세요.');showErrors('#form-errors',errors);if(errors.length)return;Object.assign(current,sanitizeQuote(draft));analyzed=structuredClone(current);renderResults();queueDraft();toast('견적 분석을 완료했습니다.');if(matchMedia('(max-width:760px)').matches)$('#results').scrollIntoView({behavior:'smooth',block:'start'});};
$('#add-addon').onclick=()=>{const count=$$('#addons [data-addon]').length;if(count>=30){toast('부가서비스는 최대 30개까지 추가할 수 있습니다.');return;}$('#addons').insertAdjacentHTML('beforeend',addonView({name:'',cost:0,months:3},count));markDirty();queueDraft();};
$('#addons').onclick=e=>{const b=e.target.closest('[data-remove-addon]');if(!b)return;const q=fromForm();q.addons.splice(Number(b.dataset.removeAddon),1);$('#addons').innerHTML=q.addons.map(addonView).join('');markDirty();queueDraft();};
f.elements.termPreset.onchange=()=>{if(f.elements.termPreset.value!=='custom')f.elements.term.value=f.elements.termPreset.value;controls.sync();markDirty();queueDraft();};
f.elements.term.oninput=()=>{const t=numericValue(f.elements.term);f.elements.termPreset.value=[0,12,24,30,36].includes(t)?String(t):'custom';};
f.elements.method.onchange=()=>{if(f.elements.method.value==='contract')f.elements.discount.value='true';if(f.elements.method.value==='subsidy'){f.elements.discount.value='false';$('#extra-discounts').open=true;}controls.sync();markDirty();queueDraft();};
$('#zero-interest').onclick=()=>{f.elements.apr.value='0';f.elements.flatFee.value='0';markDirty();queueDraft();};
const controls=bindEditorControls(f,current,fromForm,next=>{analyzed=null;bindEditor(next);$('#results').innerHTML='<section class="panel"><h2>선택한 가격을 적용했습니다.</h2><p>요금제와 추가 조건을 확인하고 분석해주세요.</p></section>';queueDraft();},()=>{markDirty();queueDraft();});
$('#keep-phone').onclick=()=>confirmAction('현재 입력을 기존 폰 유지 견적으로 바꿀까요? 남은 할부가 있다면 따로 입력해야 합니다.',()=>{const budget=Number(f.elements.budget.value.replaceAll(',',''))||0;saveId=null;analyzed=null;bindEditor({...freshQuote(cfg.policy.discountRate),budget,model:'현재 사용 중인 휴대폰',name:'기존 폰 유지',price:0});$('#results').innerHTML='<section class="panel"><h2>기존 폰 유지 비용을 확인하세요</h2><p>사용할 월 요금을 입력하고, 남은 할부가 있으면 실제 원금과 남은 기간을 입력하세요.</p></section>';queueDraft();});if(new URLSearchParams(location.search).has('intent'))f.querySelector('.buyer-help').open=true;$('#sample').onclick=()=>confirmAction('현재 입력을 예시 견적으로 바꿀까요?',()=>{saveId=null;analyzed=null;const q={...defaultQuote(cfg.policy.discountRate),name:'통신사 견적 예시',model:'예시 스마트폰 256GB',retail:1800000,price:1800000,priceMode:'gross',method:'subsidy',subsidy:500000,plan:109000,hold:6,laterPlan:55000,addons:[{name:'콘텐츠 서비스',cost:9900,months:3},{name:'통화 서비스',cost:5500,months:2}],insurance:8000,term:24,apr:5.9};bindEditor(q);queueDraft();$('#results').innerHTML='<section class="panel"><h2>예시 조건을 불러왔습니다.</h2><p>입력을 확인한 후 내 견적 분석하기를 눌러주세요.</p></section>';});
$('#reset').onclick=()=>confirmAction('현재 입력을 지우고 새 견적을 시작할까요?',()=>{saveId=null;analyzed=null;clearEditing();bindEditor(freshQuote(cfg.policy.discountRate));$('#results').innerHTML='<section class="panel"><h2>새 견적을 입력하세요.</h2></section>';history.replaceState(null,'',location.pathname);});return controls;}
function renderResults(){if(analyzed)$('#results').innerHTML=resultView(analyzed,period,saveId,entries('compare').some(x=>x.id===saveId));}
function addCompare(q,id=null){const list=entries('compare');const existing=id?list.findIndex(x=>x.id===id):-1;const row={id:id||crypto.randomUUID(),q:structuredClone(q),period,updated:new Date().toISOString()};if(existing>=0)list[existing]=row;else{if(list.length>=3){toast('최대 3개입니다. 비교 페이지에서 기존 견적을 제거해주세요.');return;}list.push(row);}if(write('compare',list)){toast('비교 목록에 추가했습니다.');renderComparison();}}
function renderSaved(){if(!$('#saved-list'))return;const list=entries('saved');$('#saved-list').innerHTML=list.length?`<div class="quote-list">${list.map(x=>`<div class="saved-item"><div><strong>${esc(x.q.name)}</strong><span class="small">${esc(x.q.model)} · ${x.period}개월 ${money(calculateTotalCost(x.q,x.period).total)}</span></div><div class="actions"><button data-saved="load" data-id="${esc(x.id)}">불러오기</button><button data-saved="compare" data-id="${esc(x.id)}">비교 추가</button><button data-saved="rename" data-id="${esc(x.id)}">이름 변경</button><button data-saved="delete" data-id="${esc(x.id)}" class="danger">삭제</button></div></div>`).join('')}</div>`:'<div class="empty">아직 저장한 견적이 없습니다. 계산 후 ‘견적 저장’을 눌러보세요.</div>';}
function renderComparison(){if(!$('#comparison'))return;$$('[data-compare-period]').forEach(x=>{x.classList.toggle('active',Number(x.dataset.comparePeriod)===comparePeriod);x.setAttribute('aria-pressed',String(Number(x.dataset.comparePeriod)===comparePeriod));});const list=entries('compare');if(!list.length){$('#comparison').innerHTML=`<div class="panel empty"><h2>비교할 견적을 모아보세요.</h2><p>계산 결과의 ‘비교에 추가’ 또는 저장한 견적의 ‘비교 추가’를 이용하세요.</p><a class="button" href="${route('/calculator')}">첫 견적 입력하기</a></div>`;return;}const results=list.map(x=>calculateTotalCost(x.q,comparePeriod)),min=Math.min(...results.map(r=>r.total));const winners=list.filter((_,i)=>results[i].total===min);const rows=[['첫 달 예상 지출','first'],['가장 많이 내는 달','peak'],['기기 원금','device'],['통신요금','plan'],['부가서비스','addons'],['보험','insurance'],['기간 내 할부 비용','interest'],['카드 연회비','cardFee'],['카드 할인 (차감)','card'],['기간 내 지출','cash'],['남은 할부원금','remaining'],['이후 이자 (합계 제외)','futureFee'],['총비용','total'],['월평균 부담','average']];$('#comparison').innerHTML=`<section class="panel"><div class="section-head"><h2>${comparePeriod}개월 비교 결과</h2><span class="badge">${list.length} / 3개</span></div>${list.length>1?`<div class="info-note"><strong>${esc(winners.map(x=>x.q.name).join(', '))}</strong> · 입력한 견적 중 ${comparePeriod}개월 총비용이 ${winners.length>1?'공동으로 ':''}가장 낮습니다. 최고 비용과의 차이는 ${money(Math.max(...results.map(r=>r.total))-min)}입니다.</div>`:'<p class="hint">견적을 하나 더 추가하면 총비용 차이를 확인할 수 있습니다.</p>'}<p class="info-note warning">비용이 낮아도 성능·데이터량·통신망·구매 조건이 같다는 뜻은 아닙니다. 아래 조건을 먼저 확인하세요.</p><div class="table-scroll" tabindex="0" role="region" aria-label="견적 비교표"><table><caption>같은 기간의 입력 조건 비교</caption><thead><tr><th scope="col">항목</th>${list.map((x,i)=>`<th scope="col"><strong>${esc(x.q.name)}</strong><br><span class="small">${esc(x.q.model)}</span><div class="compare-condition">${x.q.cashOnly?'<strong class="badge">조건부 혜택 · 일시불</strong>':'<span class="badge">입력 조건 기준</span>'}${x.q.priceNote?`<details><summary>가격 출처·구매 조건</summary><p>${esc(x.q.priceNote)}</p></details>`:''}<p>${x.q.planMode==='fixed'?`월 ${money(x.q.plan)}`:`${x.q.hold}개월 ${money(x.q.plan)} → ${money(x.q.laterPlan)}`} · ${x.q.term?x.q.term+'개월 할부':'일시불'}</p>${x.q.budget?`<p>예산 ${money(x.q.budget)}<br>${results[i].budgetGap>0?'초과 '+money(results[i].budgetGap):'남음 '+money(-results[i].budgetGap)}</p>`:''}</div><button class="text-btn" data-compare-edit="${esc(x.id)}">조건 수정</button><button class="text-btn danger" data-compare-remove="${esc(x.id)}">제거</button></th>`).join('')}</tr></thead><tbody>${rows.map(([label,key])=>`<tr><th scope="row">${label}</th>${results.map(r=>`<td class="${key==='total'&&r.total===min&&list.length>1?'winner':''}">${money(r[key])}</td>`).join('')}</tr>`).join('')}</tbody></table></div></section>`;}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;
if(b.dataset.period){period=Number(b.dataset.period);renderResults();queueDraft();if(analyzed&&JSON.stringify(fromForm())!==JSON.stringify(analyzed))markDirty();}
if(b.dataset.action&&analyzed){const q=analyzed;switch(b.dataset.action){case 'save-copy':case 'save':{const asCopy=b.dataset.action==='save-copy';const targetId=asCopy?null:saveId;const list=entries('saved');if(!targetId&&list.length>=50){toast('저장 한도 50개입니다. 기존 견적을 삭제해주세요.');break;}const id=targetId||crypto.randomUUID();const row={id,q:structuredClone(q),period,updated:new Date().toISOString()},idx=list.findIndex(x=>x.id===id);if(idx>=0)list[idx]=row;else list.unshift(row);if(write('saved',list)){if(!asCopy){const comparisons=entries('compare');const ci=comparisons.findIndex(x=>x.id===id);if(ci>=0){comparisons[ci]=row;if(!write('compare',comparisons)){toast('저장했지만 비교 목록 갱신에 실패했습니다. 다시 비교에 추가해주세요.');break;}}}saveId=id;renderSaved();renderResults();queueDraft();toast(asCopy?'새 사본을 저장했습니다.':'이 브라우저에 견적을 저장했습니다.');}break;}case 'compare':addCompare(q,saveId);break;case 'link':await copy(location.origin+route('/calculator')+'#q='+encodeQuote(q,period));break;case 'text':await copy(resultText(q,period));break;case 'image':await saveImage(q,period);break;}}
if(b.dataset.saved){const list=entries('saved'),row=list.find(x=>x.id===b.dataset.id);if(!row)return;switch(b.dataset.saved){case'load':if($('#editor'))confirmAction('현재 입력을 저장한 견적으로 바꿀까요?',()=>{saveId=row.id;period=row.period||24;analyzed=structuredClone(row.q);bindEditor(row.q);renderResults();queueDraft();$('#editor').scrollIntoView();toast('저장한 견적을 불러왔습니다.');});else if(write('draft',row))location.href=route('/calculator');break;case'compare':addCompare(row.q,row.id);break;case'rename':{actionDialog('견적 이름 변경',name=>{row.q.name=name;if(write('saved',list)){if(saveId===row.id){current.name=name;$('#quote-form').elements.name.value=name;if(analyzed)analyzed.name=name;renderResults();queueDraft();}renderSaved();toast('견적 이름을 변경했습니다.');}},row.q.name);break;}case'delete':confirmAction('저장한 견적을 삭제할까요? 비교 목록의 사본은 유지됩니다.',()=>{if(write('saved',list.filter(x=>x.id!==row.id))){if(saveId===row.id)saveId=null;renderSaved();toast('삭제했습니다.');}});break;}}
if(b.dataset.comparePeriod){comparePeriod=Number(b.dataset.comparePeriod);write('comparePeriod',comparePeriod);$$('[data-compare-period]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});renderComparison();}
if(b.dataset.compareRemove){if(write('compare',entries('compare').filter(x=>x.id!==b.dataset.compareRemove)))renderComparison();}
if(b.dataset.compareEdit){const row=entries('compare').find(x=>x.id===b.dataset.compareEdit);if(row&&write('draft',{...row,period:comparePeriod}))location.href=route('/calculator');}
});
if($('#editor')){let q=freshQuote(cfg.policy.discountRate);try{if(location.hash.startsWith('#q=')){const decoded=decodeQuote(location.hash.slice(3));q=decoded.quote;period=decoded.period;toast('공유받은 조건을 불러왔습니다.');analyzed=structuredClone(q);}else{const draft=read('draft',null);if(draft){q=sanitizeQuote(draft.q);period=[24,36].includes(draft.period)?draft.period:24;saveId=draft.id;analyzed=structuredClone(q);try{localStorage.removeItem(KEYS.draft);}catch{}}}}catch(err){toast('조건을 불러올 수 없습니다: '+err.message);}bindEditor(q);renderResults();if(shouldOfferDraftRestore(analyzed,location.hash))offerDraftRestore();}
window.addEventListener('hashchange',()=>{if($('#editor')&&location.hash.startsWith('#q=')){try{const decoded=decodeQuote(location.hash.slice(3));const q=decoded.quote;period=decoded.period;saveId=null;analyzed=structuredClone(q);bindEditor(q);renderResults();toast('공유받은 조건을 불러왔습니다.');}catch(err){toast('공유 링크를 확인해주세요: '+err.message);}}});
renderSaved();renderComparison();
function comparisonTable(labels,data){return `<div class="table-scroll" tabindex="0" role="region" aria-label="비용 계산 결과"><table><thead><tr>${labels.map(x=>`<th scope="col">${x}</th>`).join('')}</tr></thead><tbody>${data.map(row=>`<tr>${row.map((x,i)=>`<${i?'td':'th scope="row"'}>${x}</${i?'td':'th'}>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
if($('#simple-form')){const f=$('#simple-form');f.addEventListener('input',()=>{if($('#simple-result').dataset.calculated){$('#simple-result').innerHTML='<section class="panel"><p class="dirty-note" role="status">입력이 바뀌었습니다. 비용 계산하기를 눌러 새 결과를 확인하세요.</p></section>';delete $('#simple-result').dataset.calculated;}});f.addEventListener('change',()=>f.dispatchEvent(new Event('input')));f.onsubmit=e=>{e.preventDefault();const errors=numericErrors(f),v=Object.fromEntries(Array.from(f.elements).filter(x=>x.name).map(x=>[x.name,x.matches('[data-number]')?numericValue(x):x.value]));if(v.months===0)errors.push('사용기간은 1개월 이상이어야 합니다.');if(v.subsidy>v.price||v.cSubsidy>v.cPrice)errors.push('지원금이 단말기 가격을 초과할 수 없습니다.');if(v.cDiscount==='true'&&v.cSubsidy>0)errors.push('선택약정은 통신사 공통지원금과 중복 적용할 수 없습니다.');showErrors('#simple-errors',errors);if(errors.length)return;let body='';
switch(f.dataset.kind){case 'installment':{const results=[12,24,30,36].map(n=>{const r=calculateInstallment(v.price,n,v.apr);return [n+'개월',money(r.monthly),money(r.fee),money(r.total)];});body='<h2>할부 기간별 납부액</h2>'+comparisonTable(['기간','첫 월 납부액','총 수수료','총 납부액'],results)+'<p class="hint">첫 월 납부액 기준입니다. 마지막 회차는 원 단위 정산으로 달라질 수 있습니다.</p>';break;}
case 'mvno':{const r=calculateMvno(v.current,v.next,v.remaining,v.penalty,v.other);body=`<span class="eyebrow">MONTHLY DIFFERENCE</span><h2>월 절감액</h2><div class="value-difference">${money(r.monthly)}</div><div class="result-stats"><div class="stat"><span>연간 절감액 (전환비용 전)</span><strong>${money(r.annual)}</strong></div><div class="stat"><span>전환 초기 비용</span><strong>${money(v.penalty+v.other)}</strong></div></div><p class="info-note">${r.breakEven===null?'월 절감액이 0 이하이므로 회수 가능한 손익분기점이 없습니다.':`손익분기점 약 <strong>${r.breakEven.toFixed(1)}개월</strong> · 완전한 월 기준 ${Math.ceil(r.breakEven)}개월째 회수`}</p><p>남은 ${v.remaining}개월 내 순절감액: <strong>${money(r.netRemaining)}</strong></p><p class="hint">음수는 변경 시 추가 부담입니다. 12개월 순절감액은 ${money(r.annual-v.penalty-v.other)}입니다.</p>`;break;}
case 'subsidy':{const p=v.price-v.subsidy+v.plan*v.months,d=v.price+v.plan*v.months-Math.round(v.plan*v.rate/100)*Math.min(v.months,v.discountMonths);body='<h2>같은 기간의 총비용</h2>'+comparisonTable(['방식',v.months+'개월 총비용','월평균'],[['지원금',money(p),money(p/v.months)],['선택약정',money(d),money(d/v.months)]])+`<p class="info-note">${p===d?'두 방식의 총비용이 같습니다.':`${p<d?'지원금':'선택약정'} 방식의 총비용이 ${money(Math.abs(p-d))} 낮습니다.`}</p><p class="hint">실제 통신사 및 판매점 계약 조건을 반드시 확인하세요.</p>`;break;}
case 'unlocked':{const q={...defaultQuote(cfg.policy.discountRate),name:'통신사',model:'비교 기기',price:v.cPrice,priceMode:'gross',subsidy:v.cSubsidy,method:v.cDiscount==='true'?'contract':'subsidy',plan:v.cPlan,hold:v.cHold,laterPlan:v.cLater,discount:v.cDiscount==='true',discountMonths:v.cDiscountMonths,addons:[{name:'부가서비스',cost:v.cAddon,months:v.cAddonMonths}]};body='<h2>구매방식별 총비용</h2>'+comparisonTable(['기간','자급제','통신사','차이'],[24,36].map(n=>{const u=v.uPrice+v.uPlan*n,c=calculateTotalCost(q,n).total;return [n+'개월',money(u),money(c),money(Math.abs(c-u))];}));body+=[24,36].map(n=>{const u=v.uPrice+v.uPlan*n,c=calculateTotalCost(q,n).total;return `<p class="info-note">${n}개월: ${u===c?'총비용이 같습니다.':`${u<c?'자급제':'통신사'}가 총 ${money(Math.abs(c-u))}, 월평균 ${money(Math.abs(c-u)/n)} 낮습니다.`}</p>`;}).join('');break;}}
$('#simple-result').innerHTML=`<section class="panel">${body}</section>`;$('#simple-result').dataset.calculated='true';toast('비교 계산을 완료했습니다.');};}
if(document.body.dataset.page==='checklist'){let saved=read('check',[]);if(!Array.isArray(saved))saved=[];$$('[data-check]').forEach(x=>x.checked=saved.includes(Number(x.dataset.check)));const update=()=>{const checked=$$('[data-check]').filter(x=>x.checked).map(x=>Number(x.dataset.check));$('#check-count').textContent=`${checked.length} / 14개 확인`;$('#check-progress').value=checked.length;return checked;};update();$$('[data-check]').forEach(x=>x.onchange=()=>write('check',update()));$('#reset-check').onclick=()=>confirmAction('체크 상태를 모두 초기화할까요?',()=>{$$('[data-check]').forEach(x=>x.checked=false);write('check',update());});$('#print-check').onclick=()=>window.print();}
if($('#clear-data'))$('#clear-data').onclick=()=>confirmAction('이 서비스의 저장 견적·비교 목록·체크 상태를 모두 삭제할까요?',()=>{try{Object.values(KEYS).forEach(k=>localStorage.removeItem(k));toast('이 서비스의 저장 데이터를 모두 삭제했습니다.');}catch{toast('저장 데이터 삭제가 차단되었습니다. 브라우저 설정에서 삭제해주세요.');}});
if($('#contact-form'))$('#contact-form').onsubmit=e=>{e.preventDefault();const message=e.target.elements.message.value.trim();if(!message){toast('문의 내용을 입력해주세요.');return;}if(cfg.contactEmail)location.href=`mailto:${encodeURIComponent(cfg.contactEmail)}?subject=${encodeURIComponent(cfg.brand+' 문의')}&body=${encodeURIComponent(message)}`;else{download(new Blob([message],{type:'text/plain;charset=utf-8'}),'문의-내용.txt');toast('문의 내용을 저장했습니다. 전송된 내용은 없습니다.');}};
if(document.modelContext?.registerTool&&$('#editor')){try{Promise.resolve(document.modelContext.registerTool({name:'read_phone_quote_analysis',title:'현재 휴대폰 견적 분석 읽기',description:'사용자가 이미 분석한 견적의 24개월과 36개월 결과를 읽습니다. 입력을 변경하거나 저장하지 않습니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(input&&Object.keys(input).length)throw new Error('입력 인수가 없는 도구입니다.');if(!analyzed)throw new Error('먼저 화면에서 견적을 분석하세요.');return [24,36].map(n=>{const r=calculateTotalCost(analyzed,n);return {months:n,total:r.total,cash:r.cash,remaining:r.remaining,average:r.average};});}})).catch(()=>{});}catch{}}
