import {field,select,addonView,esc,money} from './views.mjs';
import {catalog,offerAvailable} from './catalog.mjs';
const months=(key,label,value,help='')=>field(key,label,value,{unit:'개월',max:120,type:'integer',help});
const step=(n,title,body)=>`<section class="panel"><div class="step-title"><span class="step-num">${n}</span><h2>${title}</h2></div>${body}</section>`;
export function catalogOptions(product,capacity){
 const v=product?.variants.find(x=>x.capacity===capacity);
 return `<option value="list">할인 추가 없이 공식 가격 사용</option>${v?.offers.map(o=>`<option value="${o.id}" ${offerAvailable(product,o)?'':'disabled'}>조회한 최대 할인 ${money(v.retail-o.netPrice)} → ${money(o.netPrice)}${offerAvailable(product,o)?' (조건부)':' (확인기간 종료)'}</option>`).join('')||''}<option value="manual">내가 받은 할인 직접 입력</option>`;
}
export function catalogView(q){
 const p=catalog.find(x=>x.id===q.catalogId),v=p?.variants.find(x=>x.capacity===q.catalogCapacity);
 return `<div class="catalog-picker"><div class="section-head"><div><span class="eyebrow">가격을 몰라도 시작하세요</span><h3>모델을 고르면 가격을 불러옵니다</h3></div><span class="badge">공식 출처 · 9개 모델</span></div><p class="hint">실시간 전체 최저가가 아닌, 출처와 확인일이 있는 가격 목록입니다. 선택 후 적용 버튼을 눌러주세요.</p><div class="field-grid">${select('catalogModel','휴대폰 모델 선택',[['','모델 선택 / 직접 입력'],...catalog.map(x=>[x.id,x.name])],p?.id||'')}${select('catalogStorage','저장 용량',p?p.variants.map(x=>[x.capacity,x.capacity]):[['','모델을 먼저 선택하세요']],v?.capacity||'')}<label class="field full"><span>출고가 / 공식 판매가 선택</span><select name="catalogPrice"><option value="list">${v?money(v.retail)+' · '+p.priceLabel:'모델과 용량을 먼저 선택하세요'}</option><option value="manual">직접 입력</option></select></label><label class="field full"><span>할인 선택</span><select name="catalogOffer">${catalogOptions(p,v?.capacity)}</select></label></div><div id="catalog-info" class="catalog-info" aria-live="polite"></div><label class="inline-check" id="catalog-confirm"><input type="checkbox" name="catalogConfirm">표시된 가격·카드·색상·구매 조건을 확인했습니다</label><p class="hint">적용하면 기존 기기 가격·기기 할인·카드 할인 입력을 선택한 조건으로 바꿉니다. 월 요금과 보험은 유지합니다.</p><button type="button" id="apply-catalog" class="primary">선택한 가격 적용</button><button type="button" id="manual-price" class="text-btn">가격·할인 직접 입력</button><p id="catalog-feedback" role="status"></p></div>`;
}
export function editorView(q,cfg){return `<form id="quote-form" novalidate><div class="editor-toolbar"><span id="draft-status" class="small" role="status">입력 중인 내용은 이 기기에 임시저장됩니다.</span><div class="actions"><button type="button" id="sample" class="text-btn">예시 불러오기</button><button type="button" id="reset" class="text-btn">새 견적</button></div></div>
${step('01','휴대폰과 가격 선택',`<details class="buyer-help"><summary>내 구매 목적에 맞게 시작하기</summary><div class="buyer-paths"><p><strong>최저비용 우선</strong><br>기존 폰 유지와 새 기기 구매를 함께 비교하세요. 보급형·중고·리퍼는 실제 받은 가격을 직접 입력하고 보증·배터리 상태를 확인하세요.</p><p><strong>성능과 가격 절충</strong><br>일상·게임·촬영 중 주용도를 정하고 필요한 저장공간, 배터리, 업데이트 지원기간을 공식 사양에서 확인하세요. 현재 목록은 성능 순위가 아닙니다.</p><p><strong>고성능 기기를 저렴하게</strong><br>같은 모델·용량끼리 비교하고 카드·색상·결제 조건을 확인하세요. 혜택 없는 공식가 견적도 함께 만들어 할인 차이를 보세요.</p></div><button type="button" id="keep-phone">기존 폰 유지 견적 시작</button><p class="hint">현재 입력을 바꾸기 전에 확인합니다. 새 기기값만 0원이며 남은 할부·수리·위약금은 별도 확인하세요.</p></details>${field('budget','총 사용기간 예산 (선택 · 0은 미설정)',q.budget||0,{help:'선택한 24개월 또는 36개월 전체의 기기·통신비 합계 예산입니다. 월 예산이 아닙니다.'})}`+catalogView(q)+`<div class="field-grid">${field('name','견적 이름',q.name,{type:'text',max:80,full:true})}${field('model','휴대폰 모델명',q.model,{type:'text',max:100,full:true})}</div><div id="applied-price" class="info-note" ${q.catalogId?'':'hidden'}></div><details id="manual-device" ${q.catalogId?'':'open'}><summary>기기 가격·할인 직접 입력 / 상세 확인</summary><div class="field-grid">${field('retail','출고가 / 공식 가격 (참고)',q.retail)}${field('price','판매가격 또는 할부원금',q.price)}${select('priceMode','입력한 기기 가격 기준',[['net','할인 후 최종 원금'],['gross','할인 전 판매가격']],q.priceMode)}${field('deviceDiscount','기기 할인금액',q.deviceDiscount)}</div><p class="hint">최종 원금 모드에서는 지원금과 기기 할인을 다시 빼지 않습니다.</p></details>`)}
${step('02','구매방식과 추가 할인',`<div class="field-grid">${select('method','구매방식',[['unlocked','자급제'],['subsidy',cfg.policy.subsidyLabel+' 방식'],['contract','선택약정'],['other','기타 판매점 견적']],q.method)}</div><details id="extra-discounts" ${q.subsidy||q.extra||q.coupon||q.other||q.card||q.cardFee?'open':''}><summary>지원금·쿠폰·카드 조건 추가</summary><p class="hint">통신사 지원금은 모델·요금제·가입유형마다 다릅니다. <a href="https://www.smartchoice.or.kr/smc/service/danpageNew.do" target="_blank" rel="noopener noreferrer" class="subtle-link">공식 안내 확인 ↗</a> · 미확인 금액은 추정하여 넣지 않습니다.</p><div class="field-grid">${field('subsidy',cfg.policy.subsidyLabel,q.subsidy,{help:'선택약정과 중복하지 않는 통신사 기기 지원금입니다.'})}${field('extra','판매점 추가지원금',q.extra)}${field('coupon','쿠폰 / 프로모션 할인',q.coupon)}${field('other','기타 기기 할인',q.other)}${field('card','카드 월 청구할인',q.card,{max:1000000,help:'매월 실적 조건 충족을 가정합니다. 가격 선택에 이미 반영한 카드 혜택을 다시 넣지 마세요.'})}${months('cardMonths','카드 할인 적용기간',q.cardMonths)}${field('cardFee','카드 연회비',q.cardFee,{max:10000000})}</div></details>`)}
${step('03','요금제',`<div class="field-grid">${select('planMode','요금제 유지 방식',[['fixed','같은 요금제 계속 사용'],['staged','일정 기간 후 요금제 변경']],q.planMode)}${field('plan','월 요금제 금액',Number.isFinite(q.plan)?q.plan:'',{max:10000000,help:'선택약정 적용 전, 부가세 포함 금액입니다.'})}<div class="full field-grid" id="plan-change">${months('hold','초기 요금제 유지기간',q.hold)}${field('laterPlan','변경 후 월정액',q.laterPlan,{max:10000000})}</div></div><p id="plan-schedule" class="info-note" aria-live="polite"></p><div class="field-grid">${select('discount','선택약정 사용',[['false','사용 안 함'],['true','선택약정 적용']],q.discount)}<div id="discount-period">${months('discountMonths','할인 적용기간',q.discountMonths)}</div></div><details id="discount-settings"><summary>선택약정 고급 설정 · 할인율</summary>${field('discountRate','선택약정 할인율',q.discountRate,{unit:'%',max:100,type:'decimal'})}</details><p class="hint">기본 ${cfg.policy.discountRate}% · 기기·보험·부가서비스 제외. 36개월 전체 할인은 재약정을 가정할 때만 적용기간을 36으로 입력하세요.</p>`)}
${step('04','부가서비스와 보험',`<details ${q.addons.length?'open':''}><summary>부가서비스 ${q.addons.length?`(${q.addons.length}개)`:'추가하기'}</summary><div id="addons">${q.addons.map(addonView).join('')}</div><button type="button" id="add-addon">＋ 부가서비스 추가</button></details><details ${q.insurance?'open':''}><summary>휴대폰 보험 ${q.insurance?money(q.insurance)+'/월':'추가하기'}</summary><div class="field-grid">${field('insurance','월 보험료',q.insurance,{max:1000000})}${months('insuranceMonths','가입기간',q.insuranceMonths)}</div></details>`)}
${step('05','결제 방식',`<div class="field-grid">${select('termPreset','납부 방식',[[0,'일시불'],[12,'12개월'],[24,'24개월'],[30,'30개월'],[36,'36개월'],['custom','직접입력']],[0,12,24,30,36].includes(q.term)?q.term:'custom')}<div id="custom-term">${months('term','할부 기간',q.term)}</div></div><div id="installment-options"><div class="field-grid">${select('feeMode','할부 비용 입력 방식',[['apr','연이율 · 원리금균등'],['flat','총 수수료 직접입력']],q.feeMode)}<div id="apr-field">${field('apr','연 이율',q.apr,{unit:'%',max:100,type:'decimal'})}</div><div id="flat-fee-field">${field('flatFee','총 할부 수수료',q.flatFee)}</div></div><button type="button" id="zero-interest" class="text-btn">0% 무이자로 설정</button><p class="hint">연이율은 원리금균등, 총 수수료는 원금·수수료 균등 배분 기준입니다. 실제 계약 방식과 반올림은 다를 수 있습니다.</p></div><p id="cash-only-note" class="info-note warning" ${q.cashOnly?'':'hidden'}>선택한 혜택가는 카드 혜택을 포함할 수 있어 일시불 비교에만 사용합니다. 할부를 계산하려면 직접 입력으로 전환해 실제 할부원금과 할인 구성을 확인하세요.</p>`)}
<div id="form-errors" class="error-box" role="alert" tabindex="-1"></div><div class="analyze-bar"><button type="submit" class="primary">내 견적 분석하기 →</button><span class="hint">저장된 견적은 분석 후 별도로 보관할 수 있습니다.</span></div></form>`;}
